apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: vyos
spec:
  peerIP: 192.168.86.36
  asNumber: 64512
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: service-cidr
spec:
  serviceClusterIPs:
  - cidr: 10.43.0.0/16
