apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: vyos
spec:
  peerIP: 192.168.86.36
  asNumber: 64512
---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: service-cidr
spec:
  serviceClusterIPs:
  - cidr: 10.43.0.0/16
