apiVersion: crd.projectcalico.org/v3
kind: BGPPeer
metadata:
  name: vyos
spec:
  peerIP: 192.168.86.36
  asNumber: 64512
---
apiVersion: crd.projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: bgp
spec:
  asNumber: 64512
  serviceExternalIPs:
  - cidr: 10.43.0.0/16
